Fixed a few pep8 errors Added a verification step in the release automation file. This step should probably be somewhere at git level.

diff --git a/release b/release
--- a/release
+++ b/release
@@ -26,6 +26,19 @@ command -v rst-lint > /dev/null || {
     exit 1
 }
 
+command -v pep8 > /dev/null || {
+    echo -e "${RED}WARNING: Missing pep8 command, please run: pip install pep8${COLOR_OFF}\n"
+    exit 1
+}
+
+set +e;
+pep8 --ignore=E501 &> /dev/null  # ignore long lines ONLY
+if [ ! $? -eq 0 ]; then
+    echo -e "${RED}WARNING: You have PEP 8 violations in your code. Please fix them.${COLOR_OFF}"
+    exit 1
+fi
+set -e;
+
 if [[ "$@" != "major" ]] && [[ "$@" != "minor" ]] && [[ "$@" != "patch" ]]; then
     echo -e "${RED}WARNING: Invalid release type, must specify 'major', 'minor', or 'patch'${COLOR_OFF}\n"
     exit 1
