Add check for gitchangelog

diff --git a/release b/release
--- a/release
+++ b/release
@@ -16,6 +16,11 @@ CYAN="\033[0;36m"     # cyan
 # ensure wheel is available
 pip install wheel > /dev/null
 
+command -v gitchangelog >/dev/null 2>&1 || {
+    echo -e "${RED}WARNING: Missing gitchangelog binary, please run: pip install gitchangelog==2.2.0${COLOR_OFF}\n"
+    exit 1
+}
+
 command -v rst-lint > /dev/null || {
     echo -e "${RED}WARNING: Missing rst-lint binary, please run: pip install restructuredtext_lint${COLOR_OFF}\n"
     exit 1
