update release script

diff --git a/release b/release
--- a/release
+++ b/release
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
+set -eo pipefail; [[ $RELEASE_TRACE ]] && set -x
 
 PACKAGE_NAME='fuzzywuzzy'
+INIT_PACKAGE_NAME='fuzzywuzzy'
 PUBLIC="true"
 
 # Colors
@@ -11,6 +13,9 @@ YELLOW="\033[0;33m"   # yellow
 MAGENTA="\033[0;35m"  # magenta
 CYAN="\033[0;36m"     # cyan
 
+# ensure wheel is available
+pip install wheel > /dev/null
+
 if [[ "$@" != "major" ]] && [[ "$@" != "minor" ]] && [[ "$@" != "patch" ]]; then
     echo -e "${RED}WARNING: Invalid release type, must specify 'major', 'minor', or 'patch'${COLOR_OFF}\n"
     exit 1
@@ -18,21 +23,23 @@ fi
 
 echo -e "\n${GREEN}STARTING RELEASE PROCESS${COLOR_OFF}\n"
 
+set +e;
 git status | grep "working directory clean" &> /dev/null
 if [ ! $? -eq 0 ]; then # working directory is NOT clean
     echo -e "${RED}WARNING: You have uncomitted changes, you may have forgotten something${COLOR_OFF}\n"
     exit 1
 fi
+set -e;
 
 echo -e "${YELLOW}--->${COLOR_OFF} Updating local copy"
 git pull -q origin master
 
 echo -e "${YELLOW}--->${COLOR_OFF} Retrieving release versions"
 
-current_version=`cat ${PACKAGE_NAME}/__init__.py |grep '__version__ ='|sed 's/[^0-9.]//g'`
-major=`echo $current_version | awk '{split($0,a,"."); print a[1]}'`
-minor=`echo $current_version | awk '{split($0,a,"."); print a[2]}'`
-patch=`echo $current_version | awk '{split($0,a,"."); print a[3]}'`
+current_version=$(cat ${INIT_PACKAGE_NAME}/__init__.py |grep '__version__ ='|sed 's/[^0-9.]//g')
+major=$(echo $current_version | awk '{split($0,a,"."); print a[1]}')
+minor=$(echo $current_version | awk '{split($0,a,"."); print a[2]}')
+patch=$(echo $current_version | awk '{split($0,a,"."); print a[3]}')
 
 if [[ "$@" == "major" ]]; then
     major=$(($major + 1));
@@ -49,9 +56,12 @@ next_version="${major}.${minor}.${patch}"
 
 echo -e  "${YELLOW}   >${COLOR_OFF} ${MAGENTA}${current_version}${COLOR_OFF} -> ${MAGENTA}${next_version}${COLOR_OFF}"
 
+echo -e "${YELLOW}--->${COLOR_OFF} Ensuring readme passes lint checks (if this fails, run rst-lint)"
+rst-lint README.rst > /dev/null
+
 echo -e "${YELLOW}--->${COLOR_OFF} Creating necessary temp file"
-tempfoo=`basename $0`
-TMPFILE=`mktemp /tmp/${tempfoo}.XXXXXX` || {
+tempfoo=$(basename $0)
+TMPFILE=$(mktemp /tmp/${tempfoo}.XXXXXX) || {
     echo -e "${RED}WARNING: Cannot create temp file using mktemp in /tmp dir ${COLOR_OFF}\n"
     exit 1
 }
@@ -59,8 +69,8 @@ TMPFILE=`mktemp /tmp/${tempfoo}.XXXXXX` || {
 find_this="__version__ = '$current_version'"
 replace_with="__version__ = '$next_version'"
 
-echo -e "${YELLOW}--->${COLOR_OFF} Updating ${PACKAGE_NAME}/__init__.py"
-sed "s/$find_this/$replace_with/" ${PACKAGE_NAME}/__init__.py > $TMPFILE && mv $TMPFILE ${PACKAGE_NAME}/__init__.py
+echo -e "${YELLOW}--->${COLOR_OFF} Updating ${INIT_PACKAGE_NAME}/__init__.py"
+sed "s/$find_this/$replace_with/" ${INIT_PACKAGE_NAME}/__init__.py > $TMPFILE && mv $TMPFILE ${INIT_PACKAGE_NAME}/__init__.py
 
 find_this="${PACKAGE_NAME}.git@$current_version"
 replace_with="${PACKAGE_NAME}.git@$next_version"
@@ -81,11 +91,11 @@ fi
 
 echo -e "${YELLOW}--->${COLOR_OFF} Updating CHANGES.rst for new release"
 version_header="$next_version ($(date +%F))"
-dashes=`yes '-'|head -n ${#version_header}|tr -d '\n'`
+set +e; dashes=$(yes '-'|head -n ${#version_header}|tr -d '\n') ; set -e
 gitchangelog |sed "4s/.*/$version_header/"|sed "5s/.*/$dashes/" > $TMPFILE && mv $TMPFILE CHANGES.rst
 
 echo -e "${YELLOW}--->${COLOR_OFF} Adding changed files to git"
-git add CHANGES.rst README.rst ${PACKAGE_NAME}/__init__.py
+git add CHANGES.rst README.rst ${INIT_PACKAGE_NAME}/__init__.py
 if [ -f docs/conf.py ]; then git add docs/conf.py; fi
 
 echo -e "${YELLOW}--->${COLOR_OFF} Creating release"
@@ -100,7 +110,7 @@ git push -q origin master && git push -q --tags
 if [[ "$PUBLIC" == "true" ]]; then
     echo -e "${YELLOW}--->${COLOR_OFF} Creating python release"
     cp README.rst README
-    python setup.py sdist upload > /dev/null
+    python setup.py sdist bdist_wheel upload > /dev/null
     rm README
 fi
 
